### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Added:
- our iBoot-IDA plugin
- Binja_KC by @skr0x1c0
- ipwnder_lite by @dora2-iOS
- palera1n jailbreak
- ElleKit by @evelyneee
- existence of checkra1n 1337

Updated:
- ipsw.dev -> ipswbeta.dev

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Comment by ghost** [comment]
lmao the CI is still broken

**Comment by 0x8ff** [comment]
I downgraded the Ruby version to 3.1.x because Jekyll doesn't support Ruby 3.2 yet...

CI is still broken no matter how many times I try :P

**Comment by ghost** [comment]
Alright I'm just going to revert all the CI Fix Attempts and keep this PR open until someone else fixes it

**Review by rickmark — DISMISSED** [review]

**Comment by ghost** [comment]
????

**Comment by ghost** [comment]
is this still pushable?

**Comment by ghost** [comment]
i have my apple-knowledge fork deleted

**Comment by ghost** [comment]
I'm not sure if you wanted to keep this open or closed but apparently yes, I just successfully pushed a test commit after this:
```
$ git fetch origin pull/119/head:pr-119
```

**Comment by ghost** [comment]
i see, i'll keep this open

**Review by rickmark — APPROVED** [review]

**Review by rickmark — APPROVED** [review]

**Review by rickmark — DISMISSED** [review]

**Review by rickmark — APPROVED** [review]

**Review by rickmark — APPROVED** [review]

**Review by rickmark — DISMISSED** [review]

**Comment by rickmark** [comment]
Having trouble getting this to work, please rebase on main and push to update the PR

**Comment by rickmark** [comment]
Sorry I couldn't credit - but the underlying source repo is gone preventing rebase

**Pull request closed without merging**
